---

dependency:
  name: galaxy
  # ERROR    Computed fully qualified role name of mtail does not follow current galaxy requirements.
  # Please edit meta/main.yml and assure we can correctly determine full role name:
  enabled: False
driver:
  name: azure
platforms:
  - name: winserv2016
    az_image_offer: windowsserverdotnet
    az_image_publisher: MicrosoftWindowsServer
    az_image_sku: 'ws2016-dotnetcore'
    az_image_version: latest
    az_vm_size: 'Standard_A2'
  - name: winserv2019
    az_image_offer: WindowsServer
    az_image_publisher: MicrosoftWindowsServer
    az_image_sku: '2019-Datacenter-smalldisk'
    az_image_version: latest
    az_vm_size: 'Standard_A2'

provisioner:
  name: ansible
verifier:
  name: ansible

azure_location: Westeurope
azure_resource_group: molecule_Windows-2019-STIG_default
azure_vnet_name: vnw_molecule_Windows-2019-STIG_default
azure_subnet_name: vsw_molecule_Windows-2019-STIG_default
azure_networkinterface_name: nic_molecule_Windows-2019-STIG_default

azure_vm_user_name: "${AZ_VM_USER_NAME:-molecule}"
azure_vm_user_password: "${AZ_VM_USER_PASSWORD:-FR(P^#ERKhds1$26!}"
# molecule_azure will create an NSG by default and  open azure_remote_port in the NSG and on the local firewall.
# WinRM https port is 5986
azure_remote_port: 5986
