---
# This is an example playbook to execute Ansible tests.

#- name: Verify
#  hosts: all
#  gather_facts: false
#  tasks:
#  - name: Example assertion
#    assert:
#      that: true

- name: Verify
  hosts: all
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    ansible_user: "{{ molecule_yml.azure_vm_user_name }}"
    ansible_password: "{{ molecule_yml.azure_vm_user_password }}"
  tasks:
    - name: "Include test_Windows-2019-STIG role"
      include_role:
        name: "test_Windows-2019-STIG"
